name: "Change Docs Folder"
on: push
permissions:
  contents: write # Able to push to master like you want
jobs:
  build_and_updateDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: _SOURCE-Contents
          path: _Source
      - name: Update _Target Folder in Main Repro(Obsolete)
        uses: actions/download-artifact@v3
        with:
          name: _SOURCE-Contents #  Where artifact is stored
          path: _Target # Download path output
      - name: Refresh Docs File(with Commit)
        env: 
          CI_COMMIT_MESSAGE: CI Build Artifacts Only Docs
          CI_COMMIT_AUTHOR: Continuous Integration(CI)
        run : |
              date > generated.txt
              git config user.name Ghislain1
              git config user.email gzeleu@outlook.de   
              git add .      
              git commit  -m "${{ env.CI_COMMIT_MESSAGE }}"
              git push
 

            
        

